# version: '3.8'

# volumes:
  # kafka_volume:
    # 로컬 드라이버를 사용하는 볼륨을 정의합니다.

    # driver: local
    # Kafka 데이터는 이 볼륨에 저장됩니다. 이는 컨테이너가 재시작되거나 재배포될 때 데이터가 유지되도록 합니다.

services:
  kafka:
    image: apache/kafka:latest
    container_name: kafka1
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.31.14.224:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      # KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@172.31.14.224:9093,2@172.31.12.74:9093,3@172.31.11.125:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3


      # KAFKA_LOG_DIRS: /var/lib/kafka/data
      # Kafka 로그 데이터가 저장될 디렉토리를 지정합니다. 컨테이너 내부의 데이터 저장 경로입니다.

      # KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      # 브로커 간 통신에 사용할 리스너 이름을 설정합니다. 브로커 간 통신에 일반 텍스트 프로토콜을 사용합니다.

      # KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      # 자동으로 토픽을 생성하는 기능을 비활성화합니다. 컨트롤러 리스너 이름을 정의합니다.

      # KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      # 컨트롤러로 지정된 리스너 이름입니다.

      #KAFKA_LOG_RETENTION_MS: 300000
      # 로그 유지 기간을 밀리초 단위로 설정합니다. 이 설정에서는 5분(300,000ms)으로 설정되어 있습니다.

      # doto1 : 172.31.14.224
      # doto2 : 172.31.12.74
      # doto3 : 172.31.11.125


      #docker exec --workdir /opt/kafka/bin/ -it kafka1 sh
      #./kafka-topics.sh --bootstrap-server localhost:9092 --create --topic test-topic
      #./kafka-console-producer.sh --bootstrap-server localhost:9092 --topic test-topic
      #./kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic test-topic --from-beginning
